apiVersion: v1
kind: Secret
metadata:
  name: profile-secret
  namespace: backend-profile
data:
  MONGO_URI: bW9uZ29kYitzcnY6Ly9zb25hbDpzb25hbDExODlAY2x1c3Rlci1zb25hbC4wa3RvbmUyLm1vbmdvZGIubmV0L3NhbXBsZW1lcm4=
  #mongodb+srv://sonal:sonal1189@cluster-sonal.0ktone2.mongodb.net/samplemern
type: Opaque