apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  type: NodePort
  selector:
    app: hello-service
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 31001

---
apiVersion: v1
kind: Service
metadata:
  name: profile-service
spec:
  type: NodePort
  selector:
    app: profile-service
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
      nodePort: 31002 

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32000 